@startuml

class Adaptee
class Target
class Adapter
class Client

class Adaptee {
    + specificRequest()
}

class Adapter {
    + request()
}

class Target {
    + request()
}

Adaptee <-- Adapter
Target <|-- Adapter
Target <-- Client

@enduml
