@startuml

interface ServiceInterface
abstract class AbstractServiceClass
class ConcreteServiceClass

interface ServiceInterface {
    + serviceMethod1() : void
    + serviceMethod2() : void
    + serviceMethod3() : void
}

abstract class AbstractServiceClass {
    + serviceMethod1() : void
    + serviceMethod2() : void
    + serviceMethod3() : void
}

class ConcreteServiceClass {
    + serviceMethod1() : void
}

ServiceInterface<|...AbstractServiceClass
AbstractServiceClass<|--ConcreteServiceClass

@enduml
