@startuml

class Client
interface Logger
class FileLogger
class DataBaseLogger
interface LoggerFactory
class FileLoggerFactory
class DataBaseLoggerFactory

Logger <|... FileLogger
Logger <|... DataBaseLogger
LoggerFactory <|... FileLoggerFactory
LoggerFactory <|... DataBaseLoggerFactory
LoggerFactory <...Client
Logger <... Client
FileLogger <...FileLoggerFactory
DataBaseLogger <... DataBaseLoggerFactory

@enduml
