@startuml

abstract class Component
class ConcreteComponent
class Decorator
class ConcreteDecoratorA
class ConcreteDecoratorB

Component <|-- ConcreteComponent
Component <|-- Decorator
Component <--o Decorator
ConcreteDecoratorA --|> Decorator
ConcreteDecoratorB --|> Decorator

class Component {
    + operation()
}

class ConcreteComponent {
    + operation()
}

class Decorator {
    + operation()
}

class ConcreteDecoratorA {
    + operation()
    + addedBehavior()
}

class ConcreteDecoratorB {
    - addedState:
    + operation()
}

@enduml
