@startuml

abstract class Flyweight {
    + operation (extrinsicState)
}

class ConcreteFlyweight {
    - intrinsicState:
    + operation(extrinsicState)
}

class UnsharedConcreteFlyweight {
    - allState:
    + operation(extrinsicState)
}

class FlyweightFactory {
    - flyweights : HashMap
    + getFlyweight(String key) : Flyweight
}

Flyweight <|... ConcreteFlyweight
Flyweight <|... UnsharedConcreteFlyweight
Flyweight <--o FlyweightFactory

@enduml
